### ISSUE TITLE
CI/CD Steps for distributing the binaries

### ISSUE THREAD

**Issue by mertssmnoglu** [murat-cileli/dbee#3]
First of all, thanks for this TUI app. :rocket: It looks great. I would like to share my opinions about adding a "Build and Release" pipeline to SDLC. I detected some disadvantages.

## Current disadvantages

- Long "git clone" time because of extra load
- Untrackable binaries / Commiting 8 new compiled binaries manually

## Diving into the disadvantages

If you have slow internet connection(like me) all the KB's are important. The source of the repository includes 8 binary files and if I want to run the application, only 1 of them can run on my machine. It means there are 6-7 useless binaries for me, and I'm waiting for them to install.

Current Repo Size: `80KB` According to [GitHub API](https://api.github.com/repos/murat-cileli/dbee).size
By deleting the bin/ directory we can decrease the cloning time.

Binaries are attached with main branch. When you commit something new the binaries got outdated automatically.
Distributing the binaries "per release" is a better option.

Also, when you want to release you need to commit 8 binaries manually. 49539aac5b726c8332b60d86391906ed45962efa, c94d94915f8a701c05d0d76819e1b736fa8c6c27, 6ead4010dfbb31a9c92675988598babb6ad7886b, 9ca389741370c04b21d77135d43dbf92af8cd9f4

## Solution advice: GoReleaser

1. We can trigger a GitHub Action when a git tag pushed.
2. GoReleaser can cross-compile the app for us.
3. Also list the binaries in "Releases" page

## Advantages

- Better git clone experience
- All configurations under the single `.goreleaser.yml`
- Ability to smoothly releasing with Semantic Versioning
- Auto changelog generation between two tags

I am into contributing but first I wanted to know your roadmap.

**Comment by murat-cileli** [comment]
Hi Mert. Yes, distributing binaries via Git repository is wrong in every way. I did it temporarily until a CI/CD system was implemented. I didn't know GoReleaser existed until your post and it looks like great. Project is open to any contribution to integrate with GoReleaser.

**Comment by mertssmnoglu** [comment]
I'm running a demo pipeline on my [test repo](https://github.com/mertssmnoglu/github-actions/blob/4bdf48210d3d32a6140f6ef07e889b27c1c7df99/.github/workflows/release.yml). It handles root directory to detect go modules, but all go related files under the `src/` directory.

What do you think about moving all files to root directory? If you are interested in I can also submit a [PR](https://github.com/mertssmnoglu/fork_dbee/tree/chore/root-directory) for it.

**Comment by murat-cileli** [comment]
I will also take a look at my first opportunity. We will determine a plan depending on the situation.

**Comment by murat-cileli** [comment]
Edited lines 14, 16 and added `dir` to line 25 then it worked like a charm! Now GoReleaser is integrated and binares are removed in repo. Thank you for your suggestion and contribution.
